### ISSUE TITLE
Cannot use plugin due to strange vim behavior

### ISSUE THREAD

**Issue by alex-popov-tech** [kizza/actionmenu.nvim#10]
Hello! your plugin looks very cool, but when i tried to use it i've experienced some strange issues, could not even describe them correctly, so here is the video: https://share.getcloudapp.com/v1urKRKg

**Comment by kizza** [comment]
Sorry @alex-popov-tech I didn't recall the details of this issue - and reviewing it again now (apologies - I don't look at these often) the video has expired.  Feel free to reach out if this is still on your mind.
