### ISSUE TITLE
Could you check if this is correct?  (Calling actionmenu >= 2 times fails)

### ISSUE THREAD

**Issue by bybor** [kizza/actionmenu.nvim#20]
https://github.com/kizza/actionmenu.nvim/blob/617d91395e3f2aa68f38db42a2468c9e975695bc/autoload/actionmenu.vim#L89

I used `actionmenu.nvim` to show the list of same items, passing user selection into callback method.

If I call `actionmenu#open` again after doing the selection once, it keeps returning `-1` and it looks like the input will go into somewhere else (another window?) until I press `ESC` .

I solved this for myself by commenting out the referenced line. I don't know Vimscript, does it make sense to you?

Thank you!

**Comment by kizza** [comment]
Interesting 🤔.  Thanks for taking the time to get in touch 🙏.

I played with adding an explicit test around this case (an extended variant of [this one](https://github.com/kizza/actionmenu.nvim/blob/main/test/plugin.test.ts#L194)) but I wasn't able to replicate it 😕

Another option I tried playing with is just to run one of the examples.  Calling `call actionmenu#example()` and selecting different options each time.  Does that work as expected for you? (ie. showing different selected options echoed at the bottom?)

Feel free to add further context here (it might be something to do with `funcref` calls or... other such things.  Happy to have a look at a snipper that's failing for you.

**Comment by bybor** [comment]
Thank you for your answer!

I will try your suggestions and will get back.

That 'quit' on line 89, doesn't it stop execution?

**Comment by kizza** [comment]
> That 'quit' on line 89, doesn't it stop execution?

Yeah - it's intended to close the window (and throw away any associated state).  It was previously attempting to achieve this by runnning `<C-w>c` (the native vin close window keys).  

Interested to hear how it goes.  I'd love to replicate your experience, write a test to capture it - and fix it for good 🤓
If that `quit` line terns out to be the problem I'm considering replacing it with nvim's native `call nvim_win_close(g:actionmenu#win, v:true)` to achieve the same result perhaps.  Best of luck!

**Comment by bybor** [comment]
I finally got to testing it with `Demo()` and with `call actionmenu#example()`. It works fine with clean configuration, so something is wrong with that of mine. 

Thank you!

P.S. I found that `dkarter/bullets.vim` caused issue for me, just FYI
