### ISSUE TITLE
Wrong callback index on cancel after selecting an index once

### ISSUE THREAD

**Issue by zurp** [kizza/actionmenu.nvim#5]
Issue video: [https://www.youtube.com/watch?v=wTCMJ_Fth-U](https://www.youtube.com/watch?v=wTCMJ_Fth-U)

Description:
Using the provided `coc.nvim` example, it seems that after selecting a code-action once, the callback index changes to `0` when canceling, instead of `-1`.

**Comment by kizza** [comment]
Howdy @zurp. Happy to let you know I just pushed a commit to clear the previously selected item (so each menu popup state is unique).  Hope it works as you expect.

PS. Thanks for the effort of creating and posting a video!
